"""
Alias to the current data-contract major (v1).
Pin to traust_contracts.v1.models directly if you need
the shape fixed regardless of what "current" means later.
"""

from traust_contracts.v1.models import (
    CVSS,
    AdapterMetadata,
    AdapterResult,
    AdapterSummary,
    ComplianceAssessment,
    ComplianceScope,
    DependencyProvenance,
    Disposition,
    EvidenceBlock,
    ExternalRef,
    Finding,
    ImpactAnalysis,
    Layer,
    LayerEvent,
    LayerMetadata,
    Location,
    MetricsRecord,
    NegativeResult,
    Remediation,
    Report,
    ReviewItem,
    ScanFinding,
    ScanMetadata,
    ScanResult,
    ScanSummary,
    SeverityOverride,
    TriageReport,
    Validation,
    Verification,
    VerificationMetadata,
    VerifiedFinding,
)

__all__ = [
    "CVSS",
    "AdapterMetadata",
    "AdapterResult",
    "AdapterSummary",
    "ComplianceAssessment",
    "ComplianceScope",
    "DependencyProvenance",
    "Disposition",
    "EvidenceBlock",
    "ExternalRef",
    "Finding",
    "ImpactAnalysis",
    "Layer",
    "LayerEvent",
    "LayerMetadata",
    "Location",
    "MetricsRecord",
    "NegativeResult",
    "Remediation",
    "Report",
    "ReviewItem",
    "ScanFinding",
    "ScanMetadata",
    "ScanResult",
    "ScanSummary",
    "SeverityOverride",
    "TriageReport",
    "Validation",
    "Verification",
    "VerificationMetadata",
    "VerifiedFinding",
]
